###
POST http://localhost:3000/register
Content-Type: application/json

{
    "password": "is missing102",
    "email": "is missing10@stud.acs.upb.ro",
    "username": "is777777"
}

###
GET http://localhost:3000/

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "is missing10",
    "password": "is missing10"
}